StartupEvents.registry('block', event => {
    event.create('quantum_flux_coil_block', 'gtceu:coil')
        .temperature(11700)
        .level(16)
        .energyDiscount(16)
        .coilMaterial(() => GTMaterials.get('fluxed_iridium'))
        .hardness(5)
        .texture('kubejs:block/coils/uhv/uhv')
        .soundType('metal')
        .tier(10)

    event.create('tachyonic_lattice_coil_block', 'gtceu:coil')
        .temperature(12600)
        .level(24)
        .energyDiscount(16)
        .coilMaterial(() => GTMaterials.get('tachyonium_alloy'))
        .hardness(5)
        .texture('kubejs:block/coils/uev/uev')
        .soundType('metal')
        .tier(11)

    event.create('photonic_singularity_coil_block', 'gtceu:coil')
        .temperature(13500)
        .level(24)
        .energyDiscount(24)
        .coilMaterial(() => GTMaterials.get('photon_glass'))
        .hardness(5)
        .texture('kubejs:block/coils/uiv/coil')
        .soundType('metal')
        .tier(12)

    event.create('graviton_condenser_coil_block', 'gtceu:coil')
        .temperature(14400)
        .level(32)
        .energyDiscount(24)
        .coilMaterial(() => GTMaterials.get('gravitonium'))
        .hardness(5)
        .texture('kubejs:block/coils/uxv/uxv')
        .soundType('metal')
        .tier(13)

    event.create('cosmic_horizon_coil_block', 'gtceu:coil')
        .temperature(15300)
        .level(32)
        .energyDiscount(32)
        .coilMaterial(() => GTMaterials.get('nebulium_alloy'))
        .hardness(5)
        .texture('kubejs:block/coils/opv/coil')
        .soundType('metal')
        .tier(14)

    event.create('supra_causal_coil_block', 'gtceu:coil')
        .temperature(16200)
        .level(48)
        .energyDiscount(32)
        .coilMaterial(() => GTMaterials.get('logical_infinity'))
        .hardness(5)
        .texture('kubejs:block/coils/max/max')
        .soundType('metal')
        .tier(15)

    event.create('ontological_collapse_coil_block', 'gtceu:coil')
        .temperature(17100)
        .level(48)
        .energyDiscount(48)
        .coilMaterial(() => GTMaterials.get('paradoxium'))
        .hardness(5)
        .texture('kubejs:block/coils/max1/akashic_coil_block')
        .soundType('metal')
        .tier(16)

    event.create('transcendental_void_coil_block', 'gtceu:coil')
        .temperature(18000)
        .level(64)
        .energyDiscount(48)
        .coilMaterial(() => GTMaterials.get('oblivium'))
        .hardness(5)
        .texture('kubejs:block/coils/max2/coil')
        .soundType('metal')
        .tier(17)

    event.create('mindwave_resonance_coil_block', 'gtceu:coil')
        .temperature(18900)
        .level(64)
        .energyDiscount(64)
        .coilMaterial(() => GTMaterials.get('psythonium'))
        .hardness(5)
        .texture('kubejs:block/coils/max3/max3')
        .soundType('metal')
        .tier(18)

    event.create('acausal_singularity_coil_block', 'gtceu:coil')
        .temperature(99999)
        .level(92)
        .energyDiscount(64)
        .coilMaterial(() => GTMaterials.get('singularium'))
        .hardness(5)
        .texture('kubejs:block/coils/max4/coil')
        .soundType('metal')
        .tier(19)

})