GTCEuStartupEvents.registry('gtceu:dimension_marker', event => {
    event.create('ad_astra:earth_orbit')
        .iconSupplier(() => Item.of('ad_astra:earth_globe').getItem())
        .tier(0)
        .overrideName('§bEarth Orbit')
    event.create('undergarden:undergarden')
        .iconSupplier(() => Item.of('undergarden:depthrock').getItem())
        .tier(0)
        .overrideName('§bThe Undergarden')
    event.create('aether:the_aether')
        .iconSupplier(() => Item.of('aether:aether_portal_frame').getItem())
        .tier(0)
        .overrideName('§bThe Aether')
    event.create('ad_astra:moon')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(1)
        .overrideName('§bThe Moon')
    event.create('ad_astra:moon_orbit')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(1)
        .overrideName('§bMoon Orbit')
    event.create('ad_astra:mars')
        .iconSupplier(() => Item.of('ad_astra:mars_globe').getItem())
        .tier(2)
        .overrideName('§bMars')
    event.create('ad_astra:mars_orbit')
        .iconSupplier(() => Item.of('ad_astra:mars_globe').getItem())
        .tier(2)
        .overrideName('§bMars Orbit')
    event.create('ad_astra:venus')
        .iconSupplier(() => Item.of('ad_astra:venus_globe').getItem())
        .tier(3)
        .overrideName('§bVenus')
    event.create('ad_astra:venus_orbit')
        .iconSupplier(() => Item.of('ad_astra:venus_globe').getItem())
        .tier(3)
        .overrideName('§bVenus Orbit')
    event.create('ad_astra:mercury')
        .iconSupplier(() => Item.of('ad_astra:mercury_globe').getItem())
        .tier(3)
        .overrideName('§bMercury')
    event.create('ad_astra:mercury_orbit')
        .iconSupplier(() => Item.of('ad_astra:mercury_globe').getItem())
        .tier(3)
        .overrideName('§bMercury Orbit')
    event.create('ad_astra:glacio')
        .iconSupplier(() => Item.of('ad_astra:glacio_globe').getItem())
        .tier(4)
        .overrideName('§bGlacio')
    event.create('ad_astra:glacio_orbit')
        .iconSupplier(() => Item.of('ad_astra:glacio_globe').getItem())
        .tier(4)
        .overrideName('§bGlacio Orbit')
    event.create('deeperdarker:otherside')
        .iconSupplier(() => Item.of('minecraft:sculk_shrieker').getItem())
        .tier(4)
        .overrideName('§bOtherside')
    event.create('sgjourney:abydos')
        .iconSupplier(() => Item.of('minecraft:sand').getItem())
        .tier(5)
        .overrideName('§bAbydos')
    event.create('sgjourney:chulak')
        .iconSupplier(() => Item.of('minecraft:oak_leaves').getItem())
        .tier(5)
        .overrideName('§bChulak')
    event.create('sgjourney:cavum_tenebrae')
        .iconSupplier(() => Item.of('botania:black_hole_talisman').getItem())
        .tier(5)
        .overrideName('§bCavum Tenebrae')
    event.create('sgjourney:lantea')
        .iconSupplier(() => Item.of('botania:water_bowl').getItem())
        .tier(6)
        .overrideName('§bLantea')
    
})