//priority = 100

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('primitive_void_mining')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(2, 2, 1, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MINER)

    event.create('primitive_smelting')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(1, 1, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.FURNACE)

    event.create('primitive_sieving')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(2, 8, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MACERATOR)

    event.create('primitive_panning')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(2, 8, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.COOLING)

    event.create('primitive_crushing')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(2, 2, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MACERATOR)

    event.create('greenhouse')
        .category('general') 
        .setEUIO('in')
        .setMaxIOSize(2, 2, 1, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.COOLING)

    event.create('large_greenhouse')
        .category('general') 
        .setEUIO('in')
        .setMaxIOSize(2, 8, 1, 0) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.COOLING)

    event.create('lcorecipe')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(4, 4, 0, 1) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.COMBUSTION)

    event.create('lpbfrecipe')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(4, 4, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.FURNACE)

    event.create('primitive_mixing')
        .category('primitive') 
        .setEUIO('in')
        .setMaxIOSize(4, 2, 2, 2) 
        .setSlotOverlay(false, false, GuiTextures.PRIMITIVE_SLOT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MIXER)

    event.create('lpsb')
        .category('lv') 
        .setEUIO('in')
        .setMaxIOSize(3, 0, 1, 2) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.BOILER)

    event.create('combustion_reactor')
        .category('mv') 
        .setEUIO('out')
        .setMaxIOSize(0, 0, 2, 1) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.BOILER)
        
    event.create('lpst')
        .category('lv') 
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 0) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.TURBINE)

    event.create('ipbf')
        .category('lv') 
        .setEUIO('in')
        .setMaxIOSize(8, 4, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.FURNACE)

    event.create('acausal_engine')
        .category('megastructure') 
        .setEUIO('in')
        .setMaxIOSize(15, 6, 9, 3) 
        .setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.REPLICATOR)

    event.create('drill_engine')
        .category('megastructure') 
        .setEUIO('in')
        .setMaxIOSize(3, 15, 6, 15) 
        .setSlotOverlay(false, false, GuiTextures.CRUSHED_ORE_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MINER)

    event.create('assembler_module')
        .category('megastructure') 
        .setEUIO('in')
        .setMaxIOSize(9, 3, 6, 3) 
        .setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.ASSEMBLER)

    event.create('sludge_reclaimer')
        .category('lv')
        .setEUIO('in')
        .setMaxIOSize(3,9,3,3)
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('concentrate_extractor')
        .category('lv')
        .setEUIO('in')
        .setMaxIOSize(3,9,3,3)
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('gem_dust_extractor')
        .category('lv')
        .setEUIO('in')
        .setMaxIOSize(3,18,3,3)
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('void_extractor')
        .category('lv') 
        .setEUIO('in')
        .setMaxIOSize(4, 2, 2, 2) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.MINER)

    event.create('void_purifier')
        .category('lv') 
        .setEUIO('in')
        .setMaxIOSize(4, 2, 2, 2) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('filter_press')
        .category('lv') 
        .setEUIO('in')
        .setMaxIOSize(4, 2, 2, 2) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('large_inscriber')
        .category('mv') 
        .setEUIO('in')
        .setMaxIOSize(4, 2, 0, 0) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)


    event.create('astral_extractor')
        .category('megastructure') 
        .setEUIO('in')
        .setMaxIOSize(3, 27, 3, 12) 
        .setSlotOverlay(false, false, GuiTextures.ATOMIC_OVERLAY_1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.REPLICATOR)

    event.create('large_mineral_extractor')
        .category('megastructure')
        .setEUIO('in')
        .setMaxIOSize(3,18,3,3)
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.CHEMICAL)

    event.create('hv_steam_turbine_mb')
        .category('hv') 
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 0) 
        .setSlotOverlay(false, false, GuiTextures.EXTRACTOR_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT) 
        .setSound(GTSoundEntries.TURBINE)

    event.create('planetary_miner')
        .setMaxIOSize(1, 21, 3, 6)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('orbital_gas_siphon')
        .setMaxIOSize(1, 0, 3, 18)
        .setSound(GTSoundEntries.CENTRIFUGE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('slaughterhouse')
        .setMaxIOSize(3, 15, 3, 3)
        .setSound(GTSoundEntries.CUT)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('orbital_assembler')
        .setMaxIOSize(15, 3, 3, 3)
        .setSound(GTSoundEntries.ASSEMBLER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('biosphere')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('lithosphere_extractor')
        .setMaxIOSize(1,2,1,3)
        .setSound(GTSoundEntries.BATH)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('fermentation_vat')
        .setMaxIOSize(3,3,3,3)
        .setSound(GTSoundEntries.BATH)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('bio_reactor')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('heavy_assembler')
        .setMaxIOSize(24, 1, 0, 0)
        .setSound(GTSoundEntries.ASSEMBLER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('vacuummor')
        .setMaxIOSize(1, 1, 0, 15)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ray_receiver')
        .setMaxIOSize(2, 0, 0, 1)
        .setSound(GTSoundEntries.BOILER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ulv_miner')
        .setMaxIOSize(2, 4, 2, 2)
        .setSound(GTSoundEntries.MINER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ulv_macerator')
        .setMaxIOSize(2, 4, 0, 0)
        .setSound(GTSoundEntries.MACERATOR)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ulv_sifter')
        .setMaxIOSize(3, 6, 0, 0)
        .setSound(GTSoundEntries.CENTRIFUGE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ashen_kiln')
        .setMaxIOSize(6, 6, 2, 2)
        .setSound(GTSoundEntries.FURNACE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('washing_basin')
        .setMaxIOSize(4, 8, 1, 2)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('atmospheric_electrolyzer')
        .setMaxIOSize(4, 6, 4, 4)
        .setSound(GTSoundEntries.ELECTROLYZER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('ulv_centrifuge')
        .setMaxIOSize(4, 12, 2, 2)
        .setSound(GTSoundEntries.CENTRIFUGE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('aetherproof_furnace')
        .setMaxIOSize(4, 4, 2, 2)
        .setSound(GTSoundEntries.FURNACE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('salt_boiler')
        .setMaxIOSize(1, 1, 2, 1)
        .setSound(GTSoundEntries.BATH)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('salt_exchanger')
        .setMaxIOSize(0, 0, 2, 2)
        .setSound(GTSoundEntries.TURBINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('lava_generator')
        .setMaxIOSize(0, 0, 2, 2)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('wtf_smelter')
        .setMaxIOSize(9, 9, 6, 3)
        .setSound(GTSoundEntries.BOILER)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('quicksilver_turbine')
        .setMaxIOSize(2, 2, 2, 2)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('cryo_dynamo')
        .setMaxIOSize(2, 2, 2, 2)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('naquadria_core')
        .setMaxIOSize(2, 2, 2, 2)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    event.create('bio_fusion')
        .setMaxIOSize(2, 2, 2, 2)
        .setSound(GTSoundEntries.JET_ENGINE)
        .setEUIO('out')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)

    



    
})